[theme]
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9f9f9"
textColor = "#0d0d0d"
primaryColor = "#0d0d0d"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
fastReruns = true